doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '8'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Users/Entities'
                type: staticphp
                prefix: 'App\Modules\Users\Entities'
                alias: User