security:
  enable_authenticator_manager: true

  providers:
    users:
      entity:
        class: App\Modules\Users\Entities\User
        property: email

  password_hashers:
    App\Modules\Users\Entities\User:
      algorithm: auto

  firewalls:
      login:
        pattern: ^/api/user/login
        stateless: true
        json_login:
          username_path: email
          password_path: password
          check_path: /api/user/login
          success_handler: lexik_jwt_authentication.handler.authentication_success
          failure_handler: lexik_jwt_authentication.handler.authentication_failure

      api:
        pattern: ^/api
        stateless: true
        jwt: ~

  access_control:
    - { path: ^/api/v1/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ['ROLE_LOGGED_IN']}